version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: certreport-postgres
    environment:
      POSTGRES_DB: certreport
      POSTGRES_USER: certuser
      POSTGRES_PASSWORD: certpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database:/docker-entrypoint-initdb.d
    networks:
      - certreport-network


volumes:
  postgres_data:

networks:
  certreport-network:
    driver: bridge
